---
- name: Configure EC2 instance
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python3 (needed by Ansible)
      raw: sudo apt-get update && sudo apt-get install -y python3
      changed_when: false

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started
